include: package:flutter_lints/flutter.yaml

linter:

  rules:

analyzer:
  errors:
    todo: warning
    missing_return: error
    dead_code: error
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"