name: Flutter CI

on: push

jobs:
  tests-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.3.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Generate support files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run Linux Tests
        run: flutter test test/linux/disks_test.dart

  tests-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.3.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Run Windows Tests
        run: flutter test test/windows/disks_test.dart

  tests-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.3.2'
          architecture: x64
      - name: Install dependencies
        run: flutter pub get
      - name: Generate support files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run macOS Tests
        run: flutter test test/macos/disks_test.dart